### ISSUE TITLE
not able to use plugin

### ISSUE THREAD

**Issue by stephanos** [mathias/boot-sassc#1]
Hey there,

I'm trying to use the plugin in my project but fail so far. I searched on Clojars and found a snapshot for it:

`[cddr/boot-sassc "0.1.1-SNAPSHOT"]`

When I require the plugin

`'[boot-sassc.core :refer :all]`

I see this:

`java.io.FileNotFoundException: Could not locate boot_sassc/core__init.class or boot_sassc/core.clj on classpath:`

Can you help me with this? I'm not sure what I'm doing wrong.

**Comment by bobby** [comment]
+1 on not being able to use this, despite wanting to.  Looking into the released 0.1.1-SNAPSHOT JAR, it appears that the namespace in the released JAR is `mathias.boot-sassc`, whereas in the source it's `boot-sassc.core`.  Also, the built JAR doesn't follow the Clojure namespace rules around hyphens and underscores (i.e. it uses a hyphen in the filename, whereas it's supposed to be an underscore in filename for a hyphen in the namespace).

**Comment by mathias** [comment]
Hi,

I've been traveling away from my computer, so I missed this issue. Sorry about that. The `[cddr/boot-sassc "0.1.1-SNAPSHOT"]` version must have been pushed to Clojars by someone else.

I've been unable to push this to Clojars, and currently I don't have my computer with GPG keys, so I'll be unable to.

@micha @alandipert Any chance of moving this to boot or adzerk orgs where I'll own updating it but we release it under those orgs?

**Comment by micha** [comment]
I think we can figure something out, no worries!

**Comment by mathias** [comment]
Thanks! :tada:

**Comment by mathias** [comment]
Is this resolved now for folks? I haven't gotten the old incorrectly-named versions taken down off clojars but I can try if that is helpful.

**Comment by sansolovyov** [comment]
Works for me with no problems, I guess this can be closed.
