### ISSUE TITLE
Support indented SASS syntax

### ISSUE THREAD

**Issue by martinklepsch** [mathias/boot-sassc#5]
Should be easily doable using `sass-convert` which is part of libsass.

**Comment by rabidpraxis** [comment]
Im not sure if this is a new change to libsass/sassc but my sass style files are compiling just fine

**Comment by martinklepsch** [comment]
@rabidpraxis ah ok. I thought I tried it but I'll give it another spin. Will reopen or create a new issue if it's not working for me. Thanks :)
