### ISSUE TITLE
Release 0.1.3 in not pushed to clojars

### ISSUE THREAD

**Issue by alesya-h** [mathias/boot-sassc#9]
I see 0.1.3 in the source repo and in README, but when I add it I get

```
org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact mathias:boot-sassc:jar:0.1.3 in clojars (https://clojars.org/repo/)
```

Could you please push it to clojars? Thank you.

**Comment by alesya-h** [comment]
Also the dependency in readme should state `[boot-sassc "0.1.X"]` instead of `[mathias/boot-sassc "0.1.X"]`

**Comment by mathias** [comment]
Hello, I'm working on a change that would standardize on mathias/boot-sassc
to match the Boot recommendations for naming. Looks like that release
didn't get fully deployed to clojars; I will try again tonight to get
everything under the right name.

On Monday, July 27, 2015, Ales Guzik notifications@github.com wrote:

> Also the dependency in readme should state [boot-sassc "0.1.X"] instead
> of [mathias/boot-sassc "0.1.X"]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mathias/boot-sassc/issues/9#issuecomment-125341904.

## 

Matt Gauger

**Comment by mathias** [comment]
I'm trying to push a `0.1.4` to clojars and getting `ReasonPhrase:Forbidden.` on it, so I need to find out why Clojars doesn't want me to push this.

**Comment by mathias** [comment]
See if you can use 0.1.4 now? (Includes your latest 2 PRs)

**Comment by alesya-h** [comment]
Works just fine!
